version: "3"
services:
  gist-viewer-api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - LOG_LEVEL=debug
      - GITHUB_URL=https://api.github.com
